import { actionTypes as dataFetchActionTypes } from '@bufferapp/async-data-fetch';
import { actionTypes as profileSidebarActionTypes } from '@bufferapp/publish-profile-sidebar';

export const actionTypes = {
  OPEN_COMPOSER: 'OPEN_COMPOSER',
  TOGGLE_DATE_TIME_FORM: 'TOGGLE_DATE_TIME_FORM',
  COLLABORATION_DRAFT_CREATED: 'COLLABORATION_DRAFT_CREATED',
  COLLABORATION_DRAFT_EDITED: 'COLLABORATION_DRAFT_EDITED',
  COLLABORATION_DRAFT_UPDATED: 'COLLABORATION_DRAFT_UPDATED',
  COLLABORATION_DRAFT_APPROVED: 'COLLABORATION_DRAFT_APPROVED',
  COLLABORATION_DRAFT_ERROR: 'COLLABORATION_DRAFT_ERROR',
  REQUESTING_DRAFT_DELETE: 'REQUESTING_DRAFT_DELETE',
  REQUESTING_DRAFT_APPROVE: 'REQUESTING_DRAFT_APPROVE',
  REQUESTING_NEEDS_APPROVAL_UPDATE: 'REQUESTING_NEEDS_APPROVAL_UPDATE',
  COLLABORATION_CONFIRM_DELETE: 'COLLABORATION_CONFIRM_DELETE',
  COLLABORATION_DRAFT_DELETED: 'COLLABORATION_DRAFT_DELETED',
  COLLABORATION_DELETE_CANCELED: 'COLLABORATION_DELETE_CANCELED',
  COLLABORATION_DRAFT_RESCHEDULE_START: 'COLLABORATION_DRAFT_RESCHEDULE_START',
  COLLABORATION_DRAFT_RESCHEDULE_SUCCESS: 'COLLABORATION_DRAFT_RESCHEDULE_SUCCESS',
  UPDATE_USER_READ_MESSAGES: 'UPDATE_USER_READ_MESSAGES',
  UPDATE_USER_READ_MESSAGES_SUCCESS: 'UPDATE_USER_READ_MESSAGES_SUCCESS',
  FETCH_PROFILE_DRAFTS_START: 'FETCH_PROFILE_DRAFTS_START',
  FETCH_PROFILE_DRAFTS_SUCCESS: 'FETCH_PROFILE_DRAFTS_SUCCESS',
  FETCH_PROFILE_DRAFTS_ERROR: 'FETCH_PROFILE_DRAFTS_ERROR',
  CHANGE_PROFILE: 'CHANGE_PROFILE',
  SET_DRAFT_FILTER: 'SET_DRAFT_FILTER',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
};

const initialState = {
  byProfileId: {},
  showComposer: false,
  enabledApplicationModes: [],
  environment: 'production',
  editMode: false,
  editingPostId: '',
};

const profileInitialState = {
  loading: true,
  loadingMore: false,
  moreToLoad: false,
  page: 1,
  posts: {},
  total: 0,
};
