const SERVICE_TWITTER = 'twitter';
const SERVICE_FACEBOOK = 'facebook';
const SERVICE_LINKEDIN = 'linkedin';
const SERVICE_APPDOTNET = 'appdotnet';
const SERVICE_GOOGLE = 'google';
const SERVICE_PINTEREST = 'pinterest';
const SERVICE_INSTAGRAM = 'instagram';

const constants = {
  SERVICE_NAMES: [
    SERVICE_TWITTER,
    SERVICE_FACEBOOK,
    SERVICE_LINKEDIN,
    SERVICE_APPDOTNET,
    SERVICE_GOOGLE,
    SERVICE_PINTEREST,
    SERVICE_INSTAGRAM,
  ],
  SERVICE_TWITTER,
  SERVICE_FACEBOOK,
  SERVICE_LINKEDIN,
  SERVICE_APPDOTNET,
  SERVICE_GOOGLE,
  SERVICE_PINTEREST,
  SERVICE_INSTAGRAM,
};

export default constants;
